### PR TITLE
Merge Spring Rewrite (MODCAL-107)

### PR DESCRIPTION
**Pull request by ncovercash**
This PR will merge team @folio-org/bama's rewrite of this module using the Spring Way.

A list of API changes may be found [here](https://github.com/ualibweb/ua-folio-docs/tree/main/docs/mod-calendar-2.0-changes/api) -- these are minor enough and designed for backward compatibility so we have designated them a minor update (to 4.1 per semver).

Exact benchmarks are attached to the [JIRA issue](https://issues.folio.org/projects/MODCAL/issues/MODCAL-107?filter=allissues) - all endpoints had their speed greatly increased (some by as much as 1400%) or were negligibly affected.

We hope to have a version of this available on our CI shortly so that you can test it yourself (although you are welcome to clone our branch for your own local testing; see the `docs/first-install.md` for instructions on how to do this).  All of our testing has succeeded; furthermore, we have written unit and integration tests with 100% coverage, so we do not anticipate any compatibility issues.

We welcome (and encourage) reviews, questions, and comments!  Feel free to leave them here or in #bama on Slack.

---

In addition to this PR, these should be merged on the same day:

- https://github.com/folio-org/folio-integration-tests/pull/495 (Karate Integration Tests)
- https://github.com/folio-org/ui-calendar/pull/379 (UI support of new error types)

### CODE REVIEW

**Comment by ncovercash** [comment]
It looks like a number of commits got shuffled around a bit when I was squashing all our commits into those (my git-fu isn't perfect, especially when we already were using multiple branches), so a few internal development notes/artifacts were left around in some of these commits.  They've all been removed in the final version, however, if you're looking at individual commits and see something that might be off, don't be alarmed!

**Comment by ncovercash** [comment]
I am not sure where these SonarCloud issues came from after bumping the version of Spring Boot.  The API for `query` and `queryForObject` have not changed: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcOperations.html#query-java.lang.String-org.springframework.jdbc.core.RowMapper-

The `queryForObject` call is the correct syntax (as opposed to the deprecated version), and the call to `query` does not return null, so I have no idea where SonarCloud got these from.

Also, I'm not sure if I've mentioned it in this thread -- the `api-lint` errors from Jenkins are an issue with the underlying linter, rather than this spec: https://github.com/aml-org/amf/issues/1338

**Comment by dltj** [comment]
> I am not sure where these SonarCloud issues came from after bumping the version of Spring Boot. The API for `query` and `queryForObject` have not changed: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcOperations.html#query-java.lang.String-org.springframework.jdbc.core.RowMapper-
> 
> The `queryForObject` call is the correct syntax (as opposed to the deprecated version), and the call to `query` does not return null, so I have no idea where SonarCloud got these from.
> 
> Also, I'm not sure if I've mentioned it in this thread -- the `api-lint` errors from Jenkins are an issue with the underlying linter, rather than this spec: [aml-org/amf#1338](https://github.com/aml-org/amf/issues/1338)

I don't have good answers for your questions, I'm afraid.  I'm not familiar with the Spring-way of module development, but surely one of the EPAM teams would know.  Do you need help connecting with someone?

**Comment by dcrossleyau** [comment]
@ncovercash The api-lint could be silenced until your upstream bug is finalised. In Jenkinsfile, set `doApiLint = false`

**Comment by ncovercash** [comment]
@dcrossleyau I appreciate that, but I think for now I'll hold off.  I'd rather keep the commit history (relatively) cleaner and, most likely, it'll be fixed by the time this has been fully reviewed and ready to release.  If it's still an issue by that time then I'll disable the linting!

**Comment by ncovercash** [comment]
The `api-lint` false-positive was fixed (https://github.com/aml-org/amf/issues/1338), however, it seems to still have issues with parameters.

**Pull request closed without merging**
